### ISSUE TITLE
X5加载页面的时候出现OverlappingFileLockException

### ISSUE THREAD

**Issue by HanseyChan** [zuowutan/ShareX5WebViewDemo#3]
`4-24 17:55:14.218 11375 11482 W System.err: java.nio.channels.OverlappingFileLockException
04-24 17:55:14.219 11375 11482 W System.err: 	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
04-24 17:55:14.219 11375 11482 W System.err: 	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
04-24 17:55:14.219 11375 11482 W System.err: 	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1061)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.utils.f.g(FileUtil.java:1214)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.utils.f.e(FileUtil.java:1177)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.u.b(X5CoreEngine.java:229)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(QbSdk.java:727)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(QbSdk.java:3389)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.TbsDownloader.a(TbsDownloader.java:1588)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.TbsDownloader.b(TbsDownloader.java:1816)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.TbsDownloader.a(TbsDownloader.java:54)
04-24 17:55:14.219 11375 11482 W System.err: 	at com.tencent.smtt.sdk.TbsDownloader$1.handleMessage(TbsDownloader.java:1070)
04-24 17:55:14.219 11375 11482 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-24 17:55:14.219 11375 11482 W System.err: 	at android.os.Looper.loop(Looper.java:165)
04-24 17:55:14.219 11375 11482 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by HanseyChan** [comment]
能正常使用，请问有办法不让他提示异常吗？
